// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PromptForFilePath():Promise<string>;

export function PromptForFolderPath():Promise<string>;
