// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PromptForFilePath() {
  return window['go']['app']['App']['PromptForFilePath']();
}

export function PromptForFolderPath() {
  return window['go']['app']['App']['PromptForFolderPath']();
}
