// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileDiff(arg1, arg2) {
  return window['go']['app']['App']['GetFileDiff'](arg1, arg2);
}

export function GetFolderDiff(arg1, arg2) {
  return window['go']['app']['App']['GetFolderDiff'](arg1, arg2);
}

export function GetSLOC(arg1) {
  return window['go']['app']['App']['GetSLOC'](arg1);
}

export function PromptForFilePath() {
  return window['go']['app']['App']['PromptForFilePath']();
}

export function SetContext(arg1) {
  return window['go']['app']['App']['SetContext'](arg1);
}
