// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetComplexity(arg1:string):Promise<number>;

export function GetFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetFolderDiff(arg1:string,arg2:string):Promise<string>;

export function GetSLOC(arg1:string):Promise<number>;

export function PromptForFilePath():Promise<string>;

export function PromptForFolderPath():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
