// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommitDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCommitDiff'](arg1, arg2, arg3);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['app']['App']['GetFileDiff'](arg1, arg2);
}

export function GetSLOC(arg1) {
  return window['go']['app']['App']['GetSLOC'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}
