// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComplexity(arg1) {
  return window['go']['source_analysis']['SourceAnalysis']['GetComplexity'](arg1);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['source_analysis']['SourceAnalysis']['GetFileDiff'](arg1, arg2);
}

export function GetFolderDiff(arg1, arg2) {
  return window['go']['source_analysis']['SourceAnalysis']['GetFolderDiff'](arg1, arg2);
}

export function GetSLOC(arg1) {
  return window['go']['source_analysis']['SourceAnalysis']['GetSLOC'](arg1);
}
