// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetComplexity(arg1:string):Promise<number>;

export function GetFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetFolderDiff(arg1:string,arg2:string):Promise<string>;

export function GetSLOC(arg1:string):Promise<number>;
